dl_filters:
    earliest_ts_date: 2019-01-01
    latest_ts_date: 2023-07-17
    anonymization_date: "NOT NULL"
    error_code: "NULL"
    nr_selfies: 10
    participant_type: "SKINLY"

selfie_data:
    download: True
    save_dir: "/home/azureuser/localfiles/digital-twins/data/selfies"

hydra:
    mode: MULTIRUN
    sweeper:
        params:
            +model: VGG-Face, Facenet, Facenet512, OpenFace, DeepFace, DeepID, ArcFace, Dlib, SFace
            +metric: cosine, euclidean, euclidean_l2